server:
  port: 2021
spring:
  application:
    name: ms-catalogo-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dfpm-student
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        platform: postgres

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka
  instance:
    hostname: localhost